version: 2
jobs:
  build:
    docker:
      - image: korosuke613/etrobo-docker:7.2-2
        user: root
    working_directory: /home/build
    steps:
      - checkout
      - run:
          name: copy
          command: |
            cp -r src /home/hrp2/sdk/workspace/
            mv -T /home/hrp2/sdk/workspace/src/ /home/hrp2/sdk/workspace/product/ 
      - run:
          name: copy
          command: |
            cp -r src /home/hrp2/sdk/workspace/product
      - run:
          name: build
          command: |
            cd /home/hrp2/sdk/workspace/
            make_src

  test:
    docker:
      - image: korosuke613/etrobo-docker:7.2-2
        user: root
    working_directory: /home/hrp2/sdk/workspace/product
    steps:
      - checkout
      - run:
          name: gtest
          command: |
            ./test/gtest/gtest_coverage.sh
      - run:
          name: install
          command: |
            apt-get update
            apt-get install -y python3.7
            pip3 install codecov
            codecov -t $CODECOV_TOKEN

  deployment:
    docker:
      - image: korosuke613/etrobo-docker:7.2-2
        user: root
    working_directory: /home/hrp2/sdk/workspace/product
    steps:
      - checkout
      - run:
          name: install
          command: |
            apt-get update
            apt-get install -y doxygen graphviz
      - run:
          name: deploy
          command: ./.circleci/deploy_doxygen.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deployment:
          filters:
            branches:
              only: master